name: "My deployment flow"


on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      
      tag:
        type: choice
        options:
          - "choice1"
          - "choice2"
          - "choice3"
      environment:
        description: "environment name"
        type: environment
        required: true
      
     
        


jobs:
  job1:
    name: "Job1"
    runs-on: ubuntu-latest
    outputs: 
      job1_task1_output : ${{ steps.task1.outputs.task1_output }}
    steps:
      - name: "task1"
        id: task1
        env:
          tag: ${{inputs.tag}}
        run: |
          echo "task1"
          echo "task1_output=$tag" >> $GITHUB_OUTPUT
      - name: "task2"
        run: echo "task2"
  job2:
    name: "My Job2"
    needs: [job1]
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: "job2 task1"
        env:
          vars_context_value: ${{ vars.PUBLIC_URL }}
          env_context_value: ${{ env.PUBLIC_URL }}
        run: |
          echo "vars context ${{ vars.PUBLIC_URL }}"
          echo "from env context ${{env.PUBLIC_URL}}"
          echo "${{secrets.MY_SECRET}}"
          echo "repo var ${{vars.REPO_VAR_URL}}"
          echo "vars_context_value: ${vars_context_value}"
          echo "env_context_value: ${env_context_value}"
        



