name: "My deployment flow"


on:
  pull_request:
  push:

jobs:
  job1:
    name: "Job1"
    runs-on: ubuntu-latest
    outputs: 
      job1_task1_output : ${{ steps.task1.outputs.task1_output }}
    steps:
      - name: "task1"
        id: task1
        env:
          tag: ${{inputs.tag}}
        run: |
          echo "task1"
          echo "task1_output=$tag" >> $GITHUB_OUTPUT
      - name: "task2"
        run: echo "task2"
  job2:
    name: "My Job2"
    needs: [job1]
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      - name: "job2 task1"
        env:
          env_context_value: ${{ vars.PUBLIC_URL }}
        run: |
          echo "vars context ${{ vars.PUBLIC_URL }}"
          echo "env vars context value ${env_context_value}"
          echo "secret is ${{secrets.MY_SECRET}}"
          echo "${{vars.REPO_VAR_URL}}"
        



